### ISSUE TITLE
Remove opened scope

### ISSUE THREAD

**Issue by ThomasVictoria** [takanabe/add-new-issues-to-project-column#18]
Hello, I'm using this action to automate the workflow of our team project organisations and I was wondering if you would consider removing this check. (linking you the issues.go file but could also be done in pull_requests.go)

https://github.com/takanabe/github-actions-automate-projects/blob/7e5d90f7e7f5f98c62c6c1f133c6206d8d254cf9/issues.go#L47

It forbid to use this action on other event such as `labeled`. I find it restrictive as it could have many such use than just `opened` and now it can be scoped at the event definition and do not require this additional check.

**Comment by takanabe** [comment]
@ThomasVictoria 

Hi! I release v0.0.2 and you can use other events with the version!
