### ISSUE TITLE
Sort with labels

### ISSUE THREAD

**Issue by havi05** [takanabe/add-new-issues-to-project-column#25]
Hi,

would it be possible to add / change the column based on the labels?

>on:
>  issues:
>    types: ['labeled']
>  pull_request:
>    types: ['labeled']

>      if: github.event_name == 'issues' && github.event.action == 'opened'  && github.event.label.name == '<label_name>'

I am not so familiar with this.

Gamemap

**Comment by takanabe** [comment]
@Gamemap 

Sure! here is an example what you want to do https://github.com/takanabe/github-actions-automate-projects/blob/master/examples/label-based-routing.yml#L23 📝

**Comment by havi05** [comment]
Thank you.
