### ISSUE TITLE
Workflow fails in new yml

### ISSUE THREAD

**Issue by jaapio** [takanabe/add-new-issues-to-project-column#5]
it looks like they changed something in the payload:

```
2019/08/13 20:16:25 [ERROR] Failed to unmarshal JSON to Go Object: &{%!e(string="2006-01-02T15:04:05Z07:00") %!e(string="8/13/2019 8:14:39 PM") %!e(string=2006) %!e(string=/2019 8:14:39 PM") %!e(string=)}
##[error]Docker run failed with exit code 1
```

**Comment by takanabe** [comment]
@jaapio 

could you check again? I released the latest version of this action in the market place, which includes breaking changes 📝I recommend you to check the README.md again
